### ISSUE TITLE
Background Bash Tool

### ISSUE THREAD

**Issue by alckasoc** [simular-ai/Agent-S#21]
**Goal**: A background stateful bash tool that Agent-S can run arbitrary commands in and get the output from. 

**A couple of useful test cases**:
- `ls`
- `sudo ls`
- `vlc`

**Todo List**:
- [X] Understand the [Anthropic Bash Tool](https://github.com/anthropics/anthropic-quickstarts/blob/main/computer-use-demo/computer_use_demo/tools/bash.py)
- [X] Explore different background bash tool options
  - [X] visibly opening a terminal (conflicts with current app)
  - [X] using subprocess (not stateful)
  - [X] using xvfb (not working)
  - [X] writing to a file (managing external file; cumbersome)
  - [X] tmux (works!; can run in the background and can keep state and capture pane)
- [X] Implement code for installing tmux
- [X] Implement code for creating a session
- [X] Implement code for killing a session
- [X] Implement code to run a command in the tmux session
  - [X] Implement code to account for timeout and output delay (and also error handling)
  - [X] Implement code to account for sudo operations
  - [X] Implement code to save the output out with `tmux capture-pane` 
 - [X] Thoroughly test the new `run_terminal_commands` agent action function by itself
 - [x] Feed the terminal output to Agent-S in some way (not sure yet) 
 - [ ] Test on test-small-new os domain
